// Worker entry: OpenNext's generated handler serves the app, and this file
// adds the Gotenberg container that converts Word uploads to PDF.
// See https://opennext.js.org/cloudflare/howtos/custom-worker
import { Container } from "@cloudflare/containers";
// @ts-expect-error .open-next/worker.js is generated by `pnpm build`
import handler from "./.open-next/worker.js";

// Reached only through the GOTENBERG binding (src/lib/convert/docx.ts), so it
// has no public URL and needs no auth. LibreOffice needs no internet either.
export class Gotenberg extends Container {
  defaultPort = 3000;
  sleepAfter = "5m";
  enableInternet = false;
}

const worker = {
  fetch: handler.fetch,
};

export default worker;
