import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { ClerkProvider, Show, UserButton } from "@clerk/nextjs";
import Link from "next/link";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <ClerkProvider>
      <html
        lang="en"
        className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
      >
        <body className="min-h-full flex flex-col">
          <Show when="signed-in">
            <div className="flex items-center justify-between border-b border-zinc-200 px-6 py-2 dark:border-zinc-800">
              <Link href="/library" className="text-sm font-semibold">
                Marginalia
              </Link>
              <UserButton />
            </div>
          </Show>
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
